### ISSUE TITLE
In news site, `.truncate-multiline` uses deprecated `-webkit-box`

### ISSUE THREAD

**Issue by rniwa** [WebKit/Speedometer#318]
Right now, both news site tests use the following CSS rule:

```css
.truncate-multiline {
    display: -webkit-box !important;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    width: 100%;
    overflow:hidden
}
```

This would result in the deprecated flexbox layout to kick in. I don't think that's appropriate in a supposedly cross-browser benchmark.
